### ISSUE TITLE
Visibility State and URL Query Params dimension Scope

### ISSUE THREAD

**Issue by rickitan** [philipwalton/analyticsjs-boilerplate#16]
Hi Phil,

Thank you for all your work. I've started to learn more about analytics and your resources have been great. I've a question about the last two dimension on this object:

```
const dimensions = {
  TRACKING_VERSION: 'Tracking Version',
  CLIENT_ID: 'Client ID',
  WINDOW_ID: 'Window ID',
  HIT_ID: 'Hit ID',
  HIT_TIME: 'Hit Time',
  HIT_TYPE: 'Hit Type',
  HIT_SOURCE: 'Hit Source',
  VISIBILITY_STATE: 'Visibility State',
  URL_QUERY_PARAMS: 'URL Query Params',
};
```

What should the scope be? To fill this form:

![image](https://user-images.githubusercontent.com/3137417/28824435-e4e295f4-768f-11e7-9aee-74e161da0083.png)

Thank you,
-Ricardo.

**Comment by philipwalton** [comment]
Set a "Hit" scope as these values can change within a session (and thus user).

In general, if you're unsure, the safest bet is "Hit" as it's the most flexible. This [video on the Google Analytics data model](https://youtu.be/K-cqHjSQ67o) might help you better understand when to choose which.
