### ISSUE TITLE
The link to analytics/base.js may be mispointed

### ISSUE THREAD

**Issue by Raylehnhoff** [philipwalton/analyticsjs-boilerplate#3]
Currently linking to:

https://github.com/philipwalton/analyticsjs-boilerplate/blob/master/src/analytics/index.js which 404s.

Should probably resolve to:
https://github.com/philipwalton/analyticsjs-boilerplate/blob/master/src/analytics/base.js

**Comment by philipwalton** [comment]
Thanks for letting me know! This should be fixed now.
