### ISSUE TITLE
The link to multiple-tracker 404s

### ISSUE THREAD

**Issue by Raylehnhoff** [philipwalton/analyticsjs-boilerplate#4]
Pointed at:

https://github.com/philipwalton/analyticsjs-boilerplate/blob/master/src/analytics/multiple-tracker.js

Should probably resolve to:

https://github.com/philipwalton/analyticsjs-boilerplate/blob/master/src/analytics/multiple-trackers.js

**Comment by philipwalton** [comment]
Thanks for letting me know! This should be fixed now.
